# Generated by Django 6.0.4 on 2026-08-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personais', '0003_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_customer_id', models.CharField(max_length=100, unique=True)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('OVERDUE', 'Vencida'), ('CANCELED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('PENDING', 'Pendente')], default='PENDING', max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('access_until', models.DateTimeField(blank=True, null=True)),
                ('last_event_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='personais.personaltrainer', verbose_name='Personal')),
            ],
        ),
    ]
