# Generated by Django 6.0.4 on 2026-08-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
    ]
