from django.urls import path

from . import views

urlpatterns = [
    path('portal/', views.portal_home, name='portal_home'),
    path('login/', views.PortalLoginView.as_view(), name='login'),
    path('portal/registro/', views.portal_register, name='portal_register'),
    path('whatsapp/', views.WhatsAppConfigListView.as_view(),
         name='whatsapp_config_list'),
    path('whatsapp/novo/', views.WhatsAppConfigCreateView.as_view(),
         name='whatsapp_config_create'),
    path('whatsapp/<int:pk>/editar/',
         views.WhatsAppConfigUpdateView.as_view(), name='whatsapp_config_edit'),
    path('personais/', views.PersonalTrainerListView.as_view(), name='personal_list'),
    path('personais/novo/', views.personal_create, name='personal_create'),
    path('personais/<int:pk>/', views.PersonalTrainerDetailView.as_view(),
         name='personal_detail'),
    path('personais/<int:pk>/editar/',
         views.PersonalTrainerUpdateView.as_view(), name='personal_edit'),
    path('personais/<int:pk>/excluir/',
         views.PersonalTrainerDeleteView.as_view(), name='personal_delete'),
    path('personais/clientes/', views.PersonalClientListView.as_view(),
         name='personal_client_list'),
    path('personais/clientes/novo/', views.personal_client_create,
         name='personal_client_create'),
    path('personais/clientes/<int:pk>/',
         views.PersonalClientDetailView.as_view(), name='personal_client_detail'),
    path('personais/clientes/<int:pk>/editar/',
         views.personal_client_edit, name='personal_client_edit'),
    path('personais/clientes/<int:pk>/excluir/',
         views.PersonalClientDeleteView.as_view(), name='personal_client_delete'),
    path('personais/clientes/<int:pk>/enviar-academia/',
         views.move_client_to_academy, name='move_client_to_academy'),
    path('personais/treinos/', views.WorkoutListView.as_view(), name='workout_list'),
    path('personais/treinos/novo/', views.workout_create, name='workout_create'),
    path('personais/treinos/<int:pk>/',
         views.WorkoutDetailView.as_view(), name='workout_detail'),
    path('personais/treinos/<int:pk>/imprimir/',
         views.workout_print, name='workout_print'),
    path('personais/treinos/<int:pk>/enviar-whatsapp/',
         views.workout_send_whatsapp, name='workout_send_whatsapp'),
    path('personais/treinos/<int:pk>/editar/',
         views.workout_edit, name='workout_edit'),
    path('personais/treinos/<int:pk>/excluir/',
         views.WorkoutDeleteView.as_view(), name='workout_delete'),
    path('personais/exercicios/',
         views.ExerciseListView.as_view(), name='exercise_list'),
    path('personais/exercicios/novo/',
         views.exercise_create, name='exercise_create'),
    path('personais/exercicios/<int:pk>/editar/',
         views.exercise_edit, name='exercise_edit'),
    path('personais/exercicios/<int:pk>/excluir/',
         views.ExerciseDeleteView.as_view(), name='exercise_delete'),
]
