# Generated by Django 6.0.4 on 2026-05-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0005_accesslog_auth_method_accesslog_biometric_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cref', models.CharField(blank=True, max_length=30, verbose_name='CREF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personais',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('goal', models.CharField(blank=True, max_length=200, verbose_name='Objetivo')),
                ('observations', models.TextField(blank=True, verbose_name='Observacoes')),
                ('born_at', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_origin', to='academia.member', verbose_name='Aluno na academia')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='personais.personaltrainer', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Cliente do personal',
                'verbose_name_plural': 'Clientes dos personais',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do treino')),
                ('goal', models.CharField(blank=True, max_length=200, verbose_name='Objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='personais.personalclient', verbose_name='Cliente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='personais.personaltrainer', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Exercicio')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Series')),
                ('reps', models.CharField(max_length=50, verbose_name='Repeticoes')),
                ('load', models.CharField(blank=True, max_length=50, verbose_name='Carga')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Descanso (segundos)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='personais.workout', verbose_name='Treino')),
            ],
            options={
                'verbose_name': 'Exercicio do treino',
                'verbose_name_plural': 'Exercicios do treino',
                'ordering': ['order', 'id'],
            },
        ),
    ]
