# Generated by Django 6.0.4 on 2026-08-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personais', '0002_personaltrainer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('muscle_group', models.CharField(blank=True, choices=[('peito', 'Peito'), ('costas', 'Costas'), ('ombros', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('antebraco', 'Antebraço'), ('abdomen', 'Abdômen'), ('gluteo', 'Glúteo'), ('quadriceps', 'Quadríceps'), ('posterior', 'Posterior de coxa'), ('panturrilha', 'Panturrilha'), ('full_body', 'Full body'), ('cardio', 'Cardio'), ('outro', 'Outro')], max_length=30, verbose_name='Grupo muscular')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['name'],
            },
        ),
    ]
