# Generated by Django 6.0.4 on 2026-08-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personais', '0003_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
    ]
