# Generated by Django 6.0.4 on 2026-08-14 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personais', '0004_personaltrainer_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personaltrainer',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__gt', '')), fields=('cpf',), name='unique_personal_trainer_cpf'),
        ),
    ]
