# Generated by Django 6.0.4 on 2026-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personais', '0005_personaltrainer_unique_personal_trainer_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='subscription_exempt',
            field=models.BooleanField(default=False, help_text='Permite acesso sem cobrança mensal. Use apenas para contas criadas pelo administrador.', verbose_name='Isento de assinatura'),
        ),
    ]
