# Generated by Django 6.0.4 on 2026-08-17 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personais', '0006_personaltrainer_subscription_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(verbose_name='URL da Evolution API')),
                ('api_key', models.CharField(max_length=255, verbose_name='Chave da API')),
                ('instance_name', models.CharField(max_length=120, verbose_name='Nome da instância')),
                ('enabled', models.BooleanField(default=True, verbose_name='Integração ativa')),
                ('send_workout_messages', models.BooleanField(default=True, verbose_name='Permitir envio de fichas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='personais.personaltrainer', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Configuração de WhatsApp',
                'verbose_name_plural': 'Configurações de WhatsApp',
                'ordering': ['personal__first_name', 'personal__last_name'],
            },
        ),
    ]
