# Generated by Django 6.0.4 on 2026-04-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_member_city_member_complement_member_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_id',
            field=models.CharField(blank=True, help_text='Código do cartão RFID ou código de barras', max_length=50, null=True, unique=True, verbose_name='ID do Cartão'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída')], max_length=5, verbose_name='Tipo de Acesso')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('success', models.BooleanField(default=True, verbose_name='Acesso Permitido')),
                ('reason', models.CharField(blank=True, help_text='Preenchido quando acesso é negado', max_length=200, verbose_name='Motivo da Negação')),
                ('card_id', models.CharField(max_length=50, verbose_name='ID do Cartão Usado')),
                ('turnstile_id', models.CharField(blank=True, help_text='Identificador da catraca física', max_length=50, verbose_name='ID da Catraca')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.member', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
