# Generated by Django 6.0.4 on 2026-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_member_card_id_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='auth_method',
            field=models.CharField(choices=[('card', 'Cartão'), ('fingerprint', 'Impressão Digital'), ('face', 'Reconhecimento Facial'), ('card_biometric', 'Cartão + Biometria')], default='card', max_length=20, verbose_name='Método de Autenticação'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='biometric_confidence',
            field=models.FloatField(blank=True, help_text='Nível de confiança da validação biométrica (0-1)', null=True, verbose_name='Confiança Biométrica'),
        ),
        migrations.AddField(
            model_name='member',
            name='biometric_enabled',
            field=models.BooleanField(default=False, verbose_name='Biometria Ativada'),
        ),
        migrations.AddField(
            model_name='member',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Dados de reconhecimento facial (JSON)', verbose_name='Encoding Facial'),
        ),
        migrations.AddField(
            model_name='member',
            name='face_photo',
            field=models.ImageField(blank=True, help_text='Foto para reconhecimento facial', null=True, upload_to='biometric_faces/', verbose_name='Foto Facial'),
        ),
        migrations.AddField(
            model_name='member',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, help_text='Dados biométricos da impressão digital', null=True, verbose_name='Template Digital'),
        ),
    ]
