"""
Django settings for biosystem project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlsplit

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    SECRET_KEY = 'django-insecure-iq_r0a2*d*a8z3w9(l0q)a$zs-yzyk175az^5+#vx=&9b_@gx%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')


def _normalize_allowed_host(raw_host: str) -> str:
    host = raw_host.strip().strip('"').strip("'")
    if not host:
        return ''

    if '://' in host:
        host = urlsplit(host).netloc or urlsplit(host).path

    if host.startswith('['):
        closing = host.find(']')
        if closing != -1:
            return host[:closing + 1]

    if ':' in host:
        host = host.split(':', 1)[0]

    return host.strip()


raw_allowed_hosts = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'inovacore.api.br,www.inovacore.api.br,localhost,127.0.0.1,[::1]',
)
allowed_host_candidates = raw_allowed_hosts.replace(';', ',').split(',')
ALLOWED_HOSTS = [
    normalized
    for normalized in (_normalize_allowed_host(host) for host in allowed_host_candidates)
    if normalized
]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'https://inovacore.api.br,https://www.inovacore.api.br,'
        'http://inovacore.api.br,http://www.inovacore.api.br,'
        'http://inovacore.api.br:8001,http://www.inovacore.api.br:8001,'
        'https://inovacore.api.br:8001,https://www.inovacore.api.br:8001',
    ).replace(';', ',').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'academia',
    'personais',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biosystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biosystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'AcademiaDB'),
        'USER': os.environ.get('DB_USER', 'biosystem_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Inovatech2025@'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', '').strip()
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', '').strip()
EVOLUTION_API_INSTANCE = os.environ.get('EVOLUTION_API_INSTANCE', '').strip()
